name: Print Toolchains
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: |
            8
            11
            17
            21
          distribution: 'temurin'
      - name: Print toolchains.xml 
        run: |
          pwd
          cat /home/runner/work/eclipse.platform/.m2/toolchains.xml
