name: Publish Unit Test Results

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
    check:
       uses: laeubi/eclipse.platform.releng.aggregator/.github/workflows/publishTestResults.yml@unify_workflows




